title                       : Mastering Pyspark
author                      : Durga Gadiraju
copyright                   : "ITVersity, Inc"

repository:
  url                       : https://github.com/itversity/pyspark
html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
  extra_navbar              : Subscribe to our <a href="http://notifyme.itversity.com">Newsletter</a>

exclude_patterns            : [_build, README.md, "**.ipynb_checkpoints"]

execute:
  execute_notebooks         : off